# Generated by Django 2.2.4 on 2019-08-03 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alipay_balance', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='支付宝余额')),
                ('wechat_balance', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='微信余额')),
                ('paycard_balance', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='工资卡余额')),
                ('huabei_debt', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='花呗欠款')),
                ('credit_debt', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='信用卡欠款')),
                ('other', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='其他财务')),
                ('describe', models.CharField(blank=True, max_length=512, null=True, verbose_name='其他财务状况说明')),
                ('summary', models.CharField(max_length=256, verbose_name='合计余额')),
                ('record_time', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
            ],
            options={
                'verbose_name': '流水记录',
                'verbose_name_plural': '流水记录',
                'ordering': ['-id'],
            },
        ),
    ]
