# Generated by Django 2.2.4 on 2019-08-04 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dir_name', models.CharField(max_length=256, verbose_name='目录名')),
                ('parent_dir_id', models.CharField(max_length=128, verbose_name='上级目录')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '目录信息表',
                'verbose_name_plural': '目录信息表',
            },
        ),
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_time', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('file_path', models.FileField(upload_to='file/%Y/%m', verbose_name='存储路径')),
                ('file_name', models.CharField(max_length=256, verbose_name='文件名')),
                ('file_size', models.CharField(max_length=256, verbose_name='文件大小')),
                ('file_type', models.CharField(max_length=128, verbose_name='文件类型')),
                ('dir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netdisk.Directory', verbose_name='所属目录')),
            ],
            options={
                'verbose_name': '上传文件信息表',
                'verbose_name_plural': '上传文件信息表',
            },
        ),
    ]
