# Generated by Django 2.2.4 on 2019-08-16 13:42

from django.db import migrations, models
import netdisk.models


class Migration(migrations.Migration):

    dependencies = [
        ('netdisk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='file_path',
            field=models.FileField(upload_to=netdisk.models.upload_to, verbose_name='存储路径'),
        ),
    ]
