# Generated by Django 2.2.4 on 2019-08-16 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerifyRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=256, verbose_name='验证码')),
                ('code_type', models.PositiveIntegerField(choices=[(1, '激活'), (2, '找回密码')], verbose_name='验证码类型')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('send_time', models.DateTimeField(auto_now_add=True, verbose_name='发送时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '邮箱验证码',
                'verbose_name_plural': '邮箱验证码',
            },
        ),
    ]
